//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginTabel
    {
        public string userId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string SecurityAnswer { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string Status { get; set; }
    }
}
