//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginTabel
    {
        public string UserId { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public byte[] LoginPhoto { get; set; }
        public string securityQuestion { get; set; }
        public string securityAnswer { get; set; }
        public Nullable<System.DateTime> loginTime { get; set; }
    }
}
