//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string EnrollNo { get; set; }
        public string RollNo { get; set; }
        public string Name { get; set; }
        public string Father { get; set; }
        public string Mother { get; set; }
        public string Course { get; set; }
        public string Branch { get; set; }
        public string Sem { get; set; }
        public string DOB { get; set; }
        public string Age { get; set; }
        public string BloodGroup { get; set; }
        public string Aadhaar { get; set; }
        public string ResiAdd { get; set; }
        public string PrmnentAdd { get; set; }
        public string StudentMob1 { get; set; }
        public string studentMob2 { get; set; }
        public string Email { get; set; }
        public string ParentsMob { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string Gender { get; set; }
        public byte[] Photo { get; set; }
        public string SessionStart { get; set; }
        public string SessionEnd { get; set; }
        public string EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDateTime { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> updateDateTime { get; set; }
    }
}
